import type { Config } from "tailwindcss";
const withMT = require("@material-tailwind/react/utils/withMT");

const config: Config = withMT({
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        fontSecondary: "var(--color-font-secondary)",
        fontLightPrimary: "var(--color-font-light-primary)",
        fontBasePrimary: "var(--color-font-base-primary)",
        fontPrimary: "var(--color-font-primary)",
        fontPlaceholder: "var(--color-font-placeholder)",
        basePrimary: "var(--color-base-primary)",
        fontBorder: "var(--color-font-input-border)",
        fontDanger: "var(--color-font-danger)",
        fontSuccess: "var(--color-font-success)",
        fontInputLabel: "var(--color-font-input-label)",
        textLight: "var(--color-text-light)",
        deleteBin: "var(--color-font-danger-bin)",
      },
      backgroundColor: {
        primary: "var(--color-primary)",
        "primary-10": "var(--color-font-primary-10)",
        secondary: "var(--color-secondary)",
        borderPrimary: "var(--color-border-primary)",
        fontPrimary: "var(--color-font-primary)",
        basePrimary: "var(--color-base-primary)",
        danger: "var(--color-font-danger)",
        dangerLight: "var(--color-font-danger-light)",
        successLight: "var(--color-font-success-light)",
        primaryGradiantStart: "var(--color-primary-gradiant-start)",
        dashboardInprogressCard: "var(--color-dashboard-inprogress-card)",
        dashboardCriticalCard: "var(--color-dashboard-critical-card)",
        dashboardReturnCard: "var(--color-dashboard-return-card)",
        dashboardTabsCard: "var(--color-dashboard-tabs-card)",
        dashboardPaymentCard: "var(--color-dashboard-payment-card)",
        dashboardTodayCard: "var(--color-dashboard-today-card)",
        dashboardActivitiesCard: "var(--color-dashboard-activities-card)",
        fontSecondaryInput: "var(--color-font-secondary-input)",
        cardHoverBackground: "var(--color-card-hover-bg)",
        chip: "var(--color-table-header)",
      },
      borderColor: {
        themePrimary: "var(--color-font-primary)",
        primary: "var(--color-border-primary)",
        secondary: "var(--color-border-secondary)",
        table: "var(--color-border-table)",
        lightPrimary: "var(--color-border-primary-half-opacity)",
      },
      screens: {
        "3xl": "1770px",
      },
      fontSize: {
        xxs: "0.5rem",
        xs: "0.625rem",
        sm: "0.75rem",
        base: "0.875rem",
        xl: "1rem",
        "2xl": "1.125rem",
        "3xl": "1.250rem",
        "4xl": "1.375rem",
        "5xl": "1.5rem",
      },
    },
  },
  plugins: [],
});
export default config;
