import "../globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Shuttlepro",
  description: "Generated by Shuttlepro",
};

interface Params {
  locale: string;
}

const locales = ["en", "ar"];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: Params;
}) {
  if (!locales.includes(locale as any)) {
    return redirect("/en/login");
  }
  const messages = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
