import "../globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { redirect } from "next/navigation";
import NextAuthSessionProvider from "./providers/sessionProviders";

export const metadata = {
  title: "Shuttlepro",
  description: "Generated by Shuttlepro",
  icons: {
    icon: "favicon.ico",
  },
};

interface Params {
  locale: string;
}

const locales = ["en", "ar"];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: Params;
}) {
  if (!locales.includes(locale as any)) {
    return redirect("/en/login");
  }
  const messages = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <NextAuthSessionProvider>
          <body>{children}</body>
        </NextAuthSessionProvider>
      </NextIntlClientProvider>
    </html>
  );
}
